config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :musics

  root 'users#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :music
  belongs_to :user
end

app/models/music.rb
class Music < ActiveRecord::Base
  has_many :likes
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :music
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes
  has_many :playlists

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  def index
    @musics = Music.all
  end

  def new
  @music = Music.new
  end

  def create
    @music = Music.new(music_params)

    if @music.save
      redirect_to musics_path
    else
      render :new
    end
  end
  def edit
   @music = Music.find(params[:id])
  end

  def update
    @music = Music.find(params[:id])

    if @music.update_attributes(music_params)
      redirect_to musics_path
    else
      render :edit
    end
  end

  def destroy
    @music = Music.find(params[:id])
    @music.destroy
    redirect_to musics_path
  end
  private
  def music_params
    params.require(:music).permit(:genre, :artist, :songs, :bio, :song_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
   @user = User.new
  end

  def create
   @user = User.new(user_params)

    if @user.save
     redirect_to users_path
    else
      render :new
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Waves</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/musics/edit.html.erb
<center>
  <div class="add-new-song-box">
      <div class="add-title">
          <h1>Edit this song!</h1>
      </div>
      <%= form_for @music do |f| %>
          <div class="input-new-song">
              <%= f.label :artist %>
              <br>
              <%= f.text_field :artist %>
          </div>

          <div class="input-new-song">
              <%= f.label :song %>
              <br>
              <%= f.text_field :songs %>
          </div>

          <div class="input-new-song">
              <%= f.label :genre %>
              <br>
              <%= f.text_field :genre %>
          </div>

          <div class="input-new-song">
              <%= f.label :bio %>
              <br>
              <%= f.text_area :bio %>
          </div>

          <div class="input-new-song">
              <%= f.label :song_url %>
              <br>
              <%= f.url_field :song_url %>
          </div>

          <div class="input-btn">
              <%= f.submit "+" %>
          </div>
      <% end %>
      <br>
      <%= link_to "Back", musics_path %>
      <%= link_to "Edit", edit_music_path(@music) %>
      <%= link_to "Delete", :music, method: :delete, data: { confirm: "Are you sure?"} %>

  </div>
</center>

app/views/musics/index.html.erb
<center>
  <div class="main-box">
    <div class="music-title-box">
      <h1>Music</h1>
    </div>
    <br>
    <div class="index-add-new-song-btn">
      <%= link_to "Add a song", new_music_path %>
    </div>
    <% @musics.each do |music| %>
      <div class="music-post">
        <div id="index-delete-btn">
          <%= link_to "X",  music_path(music), method: :delete, data: { confirm: "Are you sure you want to delete this Song?"} %>
        </div>
        <h1><%= music.artist %></h1>
        <iframe class="video" width="80%" height="350px" src="https://www.youtube.com/embed/<%= music.song_url.split('v=')[1].split('&')[0] %>" frameborder="0" allowfullscreen></iframe>
        <h3><%= music.songs %></h3>
        <h4><%= music.genre %></h4>
        <p><%= music.bio %></p>

        <hr>
      </div>
    <% end %>
    <div class="index-add-new-song-btn">
      <%= link_to "Add a song", new_music_path %>
    </div>
  </div>
</center>

app/views/musics/new.html.erb
<center>
    <div class="add-new-song-box">
        <div class="add-title">
            <h1>Add new song!</h1>
        </div>
        <%= form_for @music do |f| %>
            <div class="input-new-song">
                <%= f.label :artist %>
                <br>
                <%= f.text_field :artist %>
            </div>

            <div class="input-new-song">
                <%= f.label :song %>
                <br>
                <%= f.text_field :songs %>
            </div>

            <div class="input-new-song">
                <%= f.label :genre %>
                <br>
                <%= f.text_field :genre %>
            </div>

            <div class="input-new-song">
                <%= f.label :bio %>
                <br>
                <%= f.text_area :bio %>
            </div>

            <div class="input-new-song">
                <%= f.label :song_url %>
                <br>
                <%= f.url_field :song_url %>
            </div>

            <div class="input-btn">
                <%= f.submit "+" %>
            </div>
        <% end %>
        <br>
        <%= link_to "Back", musics_path %>
    </div>
</center>

app/views/users/edit.html.erb
<h1>Edit yourSELF!</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :picture_url %>
        <%= f.text_field :picture_url %>
    </div>


    <%= f.submit "Submit" %>

<% end %>

<%= link_to "Back to the list!", users_path %>

app/views/users/index.html.erb
<center>

<h1>Waves</h1>
<h3>ALL USERS</h3>

<ul>
  <% @users.each do |user| %>

    <%= user.name %>
      <br>
      <img src="<%= user.picture_url %>" style="width: 100px; height: 100px"/>
      <br>
      <%= user.email %>
      <br>
      Id: <%= user.id %>
      <br>
      <%= link_to "More info", user_path(user) %>

      <hr>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Make a new User</h1>

<%= form_for @user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :picture_url %>
        <%= f.text_field :picture_url %>
    </div>


    <%= f.submit "ADD ME PLZ!" %>

<% end %>

<%= link_to "Back to the list!", users_path %>

app/views/users/show.html.erb
<div style=" height:358px; width: 100%; background-image: url(https://upload.wikimedia.org/wikipedia/en/7/7c/Waves_on_Straddie_beach.jpg);">
  <div>
    <h1> <%= @user.name %> </h1>
  </div>


<img src="<%= @user.picture_url %>" style="width: 100px; height: 100px"/>
</div>
<!-- this is where User profile will be keep -->
<br>





<%= link_to "Back to the list!", users_path %> <%= link_to "Delete", user_path, method: :delete, data: { confirm: "Are you sure?"} %>
<%= link_to "Edit me", edit_user_path(@user) %>